serverFiles:
  alerts:
    groups:
      - name: Instances
        rules:
          - alert: InstanceUP
            expr: up == 1
            for: 1m
            labels:
              severity: page
            annotations:
              description: '{{ $labels.instance }} of job {{ $labels.job }} has been up for more than 1 minute. This is a test please IGNORE'
              summary: 'Instance {{ $labels.instance }} up'
alertmanagerFiles:
  alertmanager.yml:
    route:
      receiver: slack-gospel

    receivers:
      - name: slack-gospel
        slack_configs:
         - channel: '#alerts'
           api_url: 'https://hooks.slack.com/services/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'
           send_resolved: true